/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTugasRouteImport } from './routes/app.tugas'
import { Route as AppTahfidzRouteImport } from './routes/app.tahfidz'
import { Route as AppSppRouteImport } from './routes/app.spp'
import { Route as AppSiswaRouteImport } from './routes/app.siswa'
import { Route as AppResetPasswordRouteImport } from './routes/app.reset-password'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppPerilakuRouteImport } from './routes/app.perilaku'
import { Route as AppPengaturanRouteImport } from './routes/app.pengaturan'
import { Route as AppNotifikasiRouteImport } from './routes/app.notifikasi'
import { Route as AppNilaiRouteImport } from './routes/app.nilai'
import { Route as AppMoodRouteImport } from './routes/app.mood'
import { Route as AppMateriRouteImport } from './routes/app.materi'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppLaporanRouteImport } from './routes/app.laporan'
import { Route as AppKelasRouteImport } from './routes/app.kelas'
import { Route as AppForgotPasswordRouteImport } from './routes/app.forgot-password'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCatatanRouteImport } from './routes/app.catatan'
import { Route as AppBantuanRouteImport } from './routes/app.bantuan'
import { Route as AppAnakRouteImport } from './routes/app.anak'
import { Route as AppSppIdRouteImport } from './routes/app.spp.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminTahunAjaranRouteImport } from './routes/app.admin.tahun-ajaran'
import { Route as AppAdminSppRouteImport } from './routes/app.admin.spp'
import { Route as AppAdminPengumumanRouteImport } from './routes/app.admin.pengumuman'
import { Route as AppAdminPembayaranRouteImport } from './routes/app.admin.pembayaran'
import { Route as AppAdminMapelRouteImport } from './routes/app.admin.mapel'
import { Route as AppAdminKelasRouteImport } from './routes/app.admin.kelas'
import { Route as AppAdminAuditLogRouteImport } from './routes/app.admin.audit-log'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTugasRoute = AppTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AppRoute,
} as any)
const AppTahfidzRoute = AppTahfidzRouteImport.update({
  id: '/tahfidz',
  path: '/tahfidz',
  getParentRoute: () => AppRoute,
} as any)
const AppSppRoute = AppSppRouteImport.update({
  id: '/spp',
  path: '/spp',
  getParentRoute: () => AppRoute,
} as any)
const AppSiswaRoute = AppSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppPerilakuRoute = AppPerilakuRouteImport.update({
  id: '/perilaku',
  path: '/perilaku',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifikasiRoute = AppNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppNilaiRoute = AppNilaiRouteImport.update({
  id: '/nilai',
  path: '/nilai',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodRoute = AppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriRoute = AppMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppKelasRoute = AppKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCatatanRoute = AppCatatanRouteImport.update({
  id: '/catatan',
  path: '/catatan',
  getParentRoute: () => AppRoute,
} as any)
const AppBantuanRoute = AppBantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => AppRoute,
} as any)
const AppAnakRoute = AppAnakRouteImport.update({
  id: '/anak',
  path: '/anak',
  getParentRoute: () => AppRoute,
} as any)
const AppSppIdRoute = AppSppIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTahunAjaranRoute = AppAdminTahunAjaranRouteImport.update({
  id: '/admin/tahun-ajaran',
  path: '/admin/tahun-ajaran',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSppRoute = AppAdminSppRouteImport.update({
  id: '/admin/spp',
  path: '/admin/spp',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPengumumanRoute = AppAdminPengumumanRouteImport.update({
  id: '/admin/pengumuman',
  path: '/admin/pengumuman',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPembayaranRoute = AppAdminPembayaranRouteImport.update({
  id: '/admin/pembayaran',
  path: '/admin/pembayaran',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMapelRoute = AppAdminMapelRouteImport.update({
  id: '/admin/mapel',
  path: '/admin/mapel',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKelasRoute = AppAdminKelasRouteImport.update({
  id: '/admin/kelas',
  path: '/admin/kelas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/anak': typeof AppAnakRoute
  '/app/bantuan': typeof AppBantuanRoute
  '/app/catatan': typeof AppCatatanRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/kelas': typeof AppKelasRoute
  '/app/laporan': typeof AppLaporanRoute
  '/app/login': typeof AppLoginRoute
  '/app/materi': typeof AppMateriRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nilai': typeof AppNilaiRoute
  '/app/notifikasi': typeof AppNotifikasiRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/perilaku': typeof AppPerilakuRoute
  '/app/profil': typeof AppProfilRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/siswa': typeof AppSiswaRoute
  '/app/spp': typeof AppSppRouteWithChildren
  '/app/tahfidz': typeof AppTahfidzRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/kelas': typeof AppAdminKelasRoute
  '/app/admin/mapel': typeof AppAdminMapelRoute
  '/app/admin/pembayaran': typeof AppAdminPembayaranRoute
  '/app/admin/pengumuman': typeof AppAdminPengumumanRoute
  '/app/admin/spp': typeof AppAdminSppRoute
  '/app/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/spp/$id': typeof AppSppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/anak': typeof AppAnakRoute
  '/app/bantuan': typeof AppBantuanRoute
  '/app/catatan': typeof AppCatatanRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/kelas': typeof AppKelasRoute
  '/app/laporan': typeof AppLaporanRoute
  '/app/login': typeof AppLoginRoute
  '/app/materi': typeof AppMateriRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nilai': typeof AppNilaiRoute
  '/app/notifikasi': typeof AppNotifikasiRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/perilaku': typeof AppPerilakuRoute
  '/app/profil': typeof AppProfilRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/siswa': typeof AppSiswaRoute
  '/app/spp': typeof AppSppRouteWithChildren
  '/app/tahfidz': typeof AppTahfidzRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/kelas': typeof AppAdminKelasRoute
  '/app/admin/mapel': typeof AppAdminMapelRoute
  '/app/admin/pembayaran': typeof AppAdminPembayaranRoute
  '/app/admin/pengumuman': typeof AppAdminPengumumanRoute
  '/app/admin/spp': typeof AppAdminSppRoute
  '/app/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/spp/$id': typeof AppSppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/anak': typeof AppAnakRoute
  '/app/bantuan': typeof AppBantuanRoute
  '/app/catatan': typeof AppCatatanRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/kelas': typeof AppKelasRoute
  '/app/laporan': typeof AppLaporanRoute
  '/app/login': typeof AppLoginRoute
  '/app/materi': typeof AppMateriRoute
  '/app/mood': typeof AppMoodRoute
  '/app/nilai': typeof AppNilaiRoute
  '/app/notifikasi': typeof AppNotifikasiRoute
  '/app/pengaturan': typeof AppPengaturanRoute
  '/app/perilaku': typeof AppPerilakuRoute
  '/app/profil': typeof AppProfilRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/siswa': typeof AppSiswaRoute
  '/app/spp': typeof AppSppRouteWithChildren
  '/app/tahfidz': typeof AppTahfidzRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/app/admin/kelas': typeof AppAdminKelasRoute
  '/app/admin/mapel': typeof AppAdminMapelRoute
  '/app/admin/pembayaran': typeof AppAdminPembayaranRoute
  '/app/admin/pengumuman': typeof AppAdminPengumumanRoute
  '/app/admin/spp': typeof AppAdminSppRoute
  '/app/admin/tahun-ajaran': typeof AppAdminTahunAjaranRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/spp/$id': typeof AppSppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/anak'
    | '/app/bantuan'
    | '/app/catatan'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/kelas'
    | '/app/laporan'
    | '/app/login'
    | '/app/materi'
    | '/app/mood'
    | '/app/nilai'
    | '/app/notifikasi'
    | '/app/pengaturan'
    | '/app/perilaku'
    | '/app/profil'
    | '/app/reset-password'
    | '/app/siswa'
    | '/app/spp'
    | '/app/tahfidz'
    | '/app/tugas'
    | '/app/admin/audit-log'
    | '/app/admin/kelas'
    | '/app/admin/mapel'
    | '/app/admin/pembayaran'
    | '/app/admin/pengumuman'
    | '/app/admin/spp'
    | '/app/admin/tahun-ajaran'
    | '/app/admin/users'
    | '/app/spp/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/anak'
    | '/app/bantuan'
    | '/app/catatan'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/kelas'
    | '/app/laporan'
    | '/app/login'
    | '/app/materi'
    | '/app/mood'
    | '/app/nilai'
    | '/app/notifikasi'
    | '/app/pengaturan'
    | '/app/perilaku'
    | '/app/profil'
    | '/app/reset-password'
    | '/app/siswa'
    | '/app/spp'
    | '/app/tahfidz'
    | '/app/tugas'
    | '/app/admin/audit-log'
    | '/app/admin/kelas'
    | '/app/admin/mapel'
    | '/app/admin/pembayaran'
    | '/app/admin/pengumuman'
    | '/app/admin/spp'
    | '/app/admin/tahun-ajaran'
    | '/app/admin/users'
    | '/app/spp/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/anak'
    | '/app/bantuan'
    | '/app/catatan'
    | '/app/dashboard'
    | '/app/forgot-password'
    | '/app/kelas'
    | '/app/laporan'
    | '/app/login'
    | '/app/materi'
    | '/app/mood'
    | '/app/nilai'
    | '/app/notifikasi'
    | '/app/pengaturan'
    | '/app/perilaku'
    | '/app/profil'
    | '/app/reset-password'
    | '/app/siswa'
    | '/app/spp'
    | '/app/tahfidz'
    | '/app/tugas'
    | '/app/admin/audit-log'
    | '/app/admin/kelas'
    | '/app/admin/mapel'
    | '/app/admin/pembayaran'
    | '/app/admin/pengumuman'
    | '/app/admin/spp'
    | '/app/admin/tahun-ajaran'
    | '/app/admin/users'
    | '/app/spp/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tugas': {
      id: '/app/tugas'
      path: '/tugas'
      fullPath: '/app/tugas'
      preLoaderRoute: typeof AppTugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tahfidz': {
      id: '/app/tahfidz'
      path: '/tahfidz'
      fullPath: '/app/tahfidz'
      preLoaderRoute: typeof AppTahfidzRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spp': {
      id: '/app/spp'
      path: '/spp'
      fullPath: '/app/spp'
      preLoaderRoute: typeof AppSppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/siswa': {
      id: '/app/siswa'
      path: '/siswa'
      fullPath: '/app/siswa'
      preLoaderRoute: typeof AppSiswaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reset-password': {
      id: '/app/reset-password'
      path: '/reset-password'
      fullPath: '/app/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perilaku': {
      id: '/app/perilaku'
      path: '/perilaku'
      fullPath: '/app/perilaku'
      preLoaderRoute: typeof AppPerilakuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pengaturan': {
      id: '/app/pengaturan'
      path: '/pengaturan'
      fullPath: '/app/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifikasi': {
      id: '/app/notifikasi'
      path: '/notifikasi'
      fullPath: '/app/notifikasi'
      preLoaderRoute: typeof AppNotifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nilai': {
      id: '/app/nilai'
      path: '/nilai'
      fullPath: '/app/nilai'
      preLoaderRoute: typeof AppNilaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mood': {
      id: '/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AppMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materi': {
      id: '/app/materi'
      path: '/materi'
      fullPath: '/app/materi'
      preLoaderRoute: typeof AppMateriRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/laporan': {
      id: '/app/laporan'
      path: '/laporan'
      fullPath: '/app/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kelas': {
      id: '/app/kelas'
      path: '/kelas'
      fullPath: '/app/kelas'
      preLoaderRoute: typeof AppKelasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catatan': {
      id: '/app/catatan'
      path: '/catatan'
      fullPath: '/app/catatan'
      preLoaderRoute: typeof AppCatatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bantuan': {
      id: '/app/bantuan'
      path: '/bantuan'
      fullPath: '/app/bantuan'
      preLoaderRoute: typeof AppBantuanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anak': {
      id: '/app/anak'
      path: '/anak'
      fullPath: '/app/anak'
      preLoaderRoute: typeof AppAnakRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spp/$id': {
      id: '/app/spp/$id'
      path: '/$id'
      fullPath: '/app/spp/$id'
      preLoaderRoute: typeof AppSppIdRouteImport
      parentRoute: typeof AppSppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/tahun-ajaran': {
      id: '/app/admin/tahun-ajaran'
      path: '/admin/tahun-ajaran'
      fullPath: '/app/admin/tahun-ajaran'
      preLoaderRoute: typeof AppAdminTahunAjaranRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/spp': {
      id: '/app/admin/spp'
      path: '/admin/spp'
      fullPath: '/app/admin/spp'
      preLoaderRoute: typeof AppAdminSppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/pengumuman': {
      id: '/app/admin/pengumuman'
      path: '/admin/pengumuman'
      fullPath: '/app/admin/pengumuman'
      preLoaderRoute: typeof AppAdminPengumumanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/pembayaran': {
      id: '/app/admin/pembayaran'
      path: '/admin/pembayaran'
      fullPath: '/app/admin/pembayaran'
      preLoaderRoute: typeof AppAdminPembayaranRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/mapel': {
      id: '/app/admin/mapel'
      path: '/admin/mapel'
      fullPath: '/app/admin/mapel'
      preLoaderRoute: typeof AppAdminMapelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/kelas': {
      id: '/app/admin/kelas'
      path: '/admin/kelas'
      fullPath: '/app/admin/kelas'
      preLoaderRoute: typeof AppAdminKelasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit-log': {
      id: '/app/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/app/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSppRouteChildren {
  AppSppIdRoute: typeof AppSppIdRoute
}

const AppSppRouteChildren: AppSppRouteChildren = {
  AppSppIdRoute: AppSppIdRoute,
}

const AppSppRouteWithChildren =
  AppSppRoute._addFileChildren(AppSppRouteChildren)

interface AppRouteChildren {
  AppAnakRoute: typeof AppAnakRoute
  AppBantuanRoute: typeof AppBantuanRoute
  AppCatatanRoute: typeof AppCatatanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppKelasRoute: typeof AppKelasRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMateriRoute: typeof AppMateriRoute
  AppMoodRoute: typeof AppMoodRoute
  AppNilaiRoute: typeof AppNilaiRoute
  AppNotifikasiRoute: typeof AppNotifikasiRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPerilakuRoute: typeof AppPerilakuRoute
  AppProfilRoute: typeof AppProfilRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSiswaRoute: typeof AppSiswaRoute
  AppSppRoute: typeof AppSppRouteWithChildren
  AppTahfidzRoute: typeof AppTahfidzRoute
  AppTugasRoute: typeof AppTugasRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminKelasRoute: typeof AppAdminKelasRoute
  AppAdminMapelRoute: typeof AppAdminMapelRoute
  AppAdminPembayaranRoute: typeof AppAdminPembayaranRoute
  AppAdminPengumumanRoute: typeof AppAdminPengumumanRoute
  AppAdminSppRoute: typeof AppAdminSppRoute
  AppAdminTahunAjaranRoute: typeof AppAdminTahunAjaranRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnakRoute: AppAnakRoute,
  AppBantuanRoute: AppBantuanRoute,
  AppCatatanRoute: AppCatatanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppKelasRoute: AppKelasRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppLoginRoute: AppLoginRoute,
  AppMateriRoute: AppMateriRoute,
  AppMoodRoute: AppMoodRoute,
  AppNilaiRoute: AppNilaiRoute,
  AppNotifikasiRoute: AppNotifikasiRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPerilakuRoute: AppPerilakuRoute,
  AppProfilRoute: AppProfilRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSiswaRoute: AppSiswaRoute,
  AppSppRoute: AppSppRouteWithChildren,
  AppTahfidzRoute: AppTahfidzRoute,
  AppTugasRoute: AppTugasRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminKelasRoute: AppAdminKelasRoute,
  AppAdminMapelRoute: AppAdminMapelRoute,
  AppAdminPembayaranRoute: AppAdminPembayaranRoute,
  AppAdminPengumumanRoute: AppAdminPengumumanRoute,
  AppAdminSppRoute: AppAdminSppRoute,
  AppAdminTahunAjaranRoute: AppAdminTahunAjaranRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
